### ISSUE TITLE
23andme study dyslexia

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#10]
@gaow 

I was doing my monthly search to see if 23andme study was published in a major publication. It was just published in nature genetics  [Discovery of 42 genome-wide significant loci associated with dyslexia](https://www.nature.com/articles/s41588-022-01192-y )! I will follow up with the authors in couple days if we do not get a response from 23andme with the data. 

Best,
Mia Grasso

**Comment by gaow** [comment]
@mgrasso24 great -- could you reach out to Pierre again and cc me? Please ask him what's the procedure to apply for the access, and when we would usually expect to get the data from them. Thanks!

**Comment by gaow** [comment]
The paper says: "The full summary statistics for each dyslexia GWAS presented in this paper **will be made available** through 23andMe website (https://research.23andme.com/dataset-access/) to qualified researchers under an agreement with 23andMe that protects the privacy of the 23andMe participants". "will be made available" is not reassuring .... also depending on when they review the applications this process can drag very long. I can try to push them through my connections at the company but eventually it depends on them if they can respond to it timely. When you reach out to Pierre please tell him that this is time sensitive and we would very much like to collaborate with them on a manuscript together if that helps with the access ...

**Comment by mgrasso24** [comment]
Got it! I scheduled those emails to send in the morning.
