### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    Timeout was reached: [www.ensembl.org:443] Operation timed out after 300005 milliseconds with 65451 bytes received

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#11]
@gaow 

I was running the code for the CHR and POS for Gialluisi dataset and I keep coming across this error. I am able to run the code when doing it for every 2,000 SNPs but there is 7 million of them so it would not be efficient to just run it 3,500 times. Do you have any ideas on how I can get across this limitation?

[20221112_CHR_POS_Gialluisi_et_at.(2021).ipynb](https://github.com/mgrasso24/dyslexia-omics-integration/blob/main/analysis/20221112_CHR_POS_Gialluisi_et_at.%2C(2021).ipynb)

Code for entire dataset 

```
BiocManager::install('grimbough/biomaRt')

library(biomaRt) # biomaRt_2.30.0
snp_mart = useMart("ENSEMBL_MART_SNP", dataset="hsapiens_snp")

curl::curl_fetch_memory("https://www.ensembl.org:443/biomart/martservice")

MetaAnalysis_cc1 <- read.delim("~/Downloads/MetaAnalysis_cc1.tbl", header=FALSE)
drop <- c("V9","V2","V3","V4","V5","V6","V7","V8","V10","V11")
mdf = MetaAnalysis_cc1[!(names(MetaAnalysis_cc1)%in% drop)]
mdf0 <- mdf[2:6917792, ] 
snp_ids0 = c(mdf0)


snp_attributes = c("refsnp_id", "chr_name", "chrom_start")

snp_locations = getBM(attributes=snp_attributes, filters="snp_filter",

values=snp_ids0, mart=snp_mart)
```
This results in 

> Batch submitting query [-----------------------------------------]   0% eta:  4dError in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached: [www.ensembl.org:443] Operation timed out after 300005 milliseconds with 65451 bytes received
> 

Code for 2,000 SNPs

```
BiocManager::install('grimbough/biomaRt')

library(biomaRt) # biomaRt_2.30.0
snp_mart = useMart("ENSEMBL_MART_SNP", dataset="hsapiens_snp")

curl::curl_fetch_memory("https://www.ensembl.org:443/biomart/martservice")

MetaAnalysis_cc1 <- read.delim("~/Downloads/MetaAnalysis_cc1.tbl", header=FALSE)
drop <- c("V9","V2","V3","V4","V5","V6","V7","V8","V10","V11")
mdf = MetaAnalysis_cc1[!(names(MetaAnalysis_cc1)%in% drop)]
mdf1 <- mdf[2:2000, ] 

snp_ids = c(mdf1)


snp_attributes = c("refsnp_id", "chr_name", "chrom_start")

snp_locations = getBM(attributes=snp_attributes, filters="snp_filter",

values=snp_ids, mart=snp_mart)


```

Which outputs 

> refsnp_id             chr_name  chrom_start
> 1     rs1538018                    1   162160691
> 2      rs819895                    1   245382847
> 3      rs819895 CHR_HSCHR1_1_CTG32_1   245382847
> 4      rs820622                    1    14335786
> 5      rs841865                    1   208052564
>

**Comment by gaow** [comment]
@mgrasso24 you are on the right track but I think the problem here is that we need to annotate lots of variants and that repeatedly query it does not work due to network traffic issue. In principle, what can be done is to download the dbSNP database then query it using some R or Python codes offline. https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ has the database if you check on the `snp151.txt.gz` but it is a large, 13GB file to manipulate ..

**Comment by mgrasso24** [comment]
Ok, that makes sense will download the dataset and manipulate it using some R or Python codes offline.
