### ISSUE TITLE
Update on LD for SNPs

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#12]
@gaow 

Since we last spoke you mentioned that we will need to get the LD for the SNPs in order to run coloc analysis. I have been actively searching for a method that might work to receive the LD against a smaller dataset. I originally tried using this website 

> https://analysistools.cancer.gov/LDlink/?tab=ldmatrix

but the major limitation was that it could only run for 300 SNPs. Therefore, I am going to look at the GitHub code for 

> https://github.com/CBIIT/LDlinkR

We just received the computer, so I can run the code of CHR and POS for the Gialluisi study. When we last spoke you said you would take a look at my sample code, so I was wondering if it is all good or if I need to make some changes?

**Comment by gaow** [comment]
Thanks @mgrasso24 i actually don't know the LDlinkR tool you pointed above. That's very good of you to explore these tools. 

It is terrific that you've got the computer to run the codes for the Gialluisi study. let me put it this way -- your code is reasonable and would capture overlapping variants between two data-sets. It is not the most memory efficient approach but now that you have a good computer setup, I would suggest you give it a go. 

However, there are still more aspects about it if we want to get all the analysis done completely correctly. I have some protocols in my lab that we use to do these analysis. The details are complicated to understand but the workflow and overall idea would be exactly the same as what you are being instructed to do. So here is my proposal:

1. For educational purposes, I would like you to enjoy the process of building up your analysis from available public resources including eg the software you find on your own on github. In this case, you match the SNPs, computer the LD then run COLOC, for both eQTL and Gialluisi studies. The point is to finish it even though it is computationally intensive, and not perfect (you could make mistakes and there are other details in the protocol which your code does not take into consideration at this point). This will serve the purpose to 1) let you grasp the big picture and face the major challenges in analysis without having to study too much technical details; and 2) get a version of result that you can truly claim you did it completely independently.
2. After you are done with the above, we upgrade your analysis completely: using the 23andme data-set which I am trying to push and hopefully get it within 1.5 months, and using the protocols developed in my lab, to redo the analysis better. At that point I'll instruct you with some more details (through a 1hr meeting followed by a few github tickets is enough) and hoping with what you learned from 1, you will be in a much better position to understand them. The results from that would be a lot more solid and final.

I hope you agree with this "iterative" approach in both train you properly with the skill-set and the knowledge, as well as getting the work done seriously.

**Comment by gaow** [comment]
Now, more details regarding the LD computation. I prefer an R or Python based tool rather that a webpage interface (as with the ldmatrix tool). LDlinkR seems to be a good web service with R interface, but you may still struggle when there are many SNPs involved. I would suggest you match your data-set between eQTL and GWAS and extract only the variants with p-value < 1E-5 in both studies to get the LD of those variants trying to use the LDlinkR tool (that I don't have experience with but  can still provide feedback when you show me what you have). At that point we are talking about a few thousand SNPs hopefully LDlinkR can handle and if not we can even do it manually by batches to make sure we finish all of them.

**Comment by mgrasso24** [comment]
@gaow 

> I hope you agree with this "iterative" approach in both train you properly with the skill-set and the knowledge, as well as getting the work done seriously.

This sounds great. I will get on this as soon as the computer is ready which I am predicting will be ready in a day or two!

> At that point we are talking about a few thousand SNPs hopefully LDlinkR can handle and if not we can even do it manually by batches to make sure we finish all of them.

I will get started on this and let you know how it goes!

Thank you so much for your help with advance and helping obtain the 23andme study.

**Comment by mgrasso24** [comment]
@gaow 

I am still working on getting the CHR and POS for the Gialluisi study. I am having some technical issues with the new fancy computer, but I have a meeting with the person that set up the computer on Monday. After everything is fixed I should be able to get back on track with the work!

**Comment by gaow** [comment]
okay great @mgrasso24 if you think i can be helpful with the issue please let me know!

**Comment by mgrasso24** [comment]
ok, thanks!
