### ISSUE TITLE
Error with the Hudson Plot 

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#4]
I ran this code to create the Hudson Plot in Rstudio

```
# Create a basic plot with Bonferroni lines and highlighting using the gwas and eQTL datasets
install.packages("devtools")
devtools::install_github("hadley/devtools")
devtools::install_github('anastasia-lucas/hudson')
library(hudson)
MetaAnalysis_cc1 <- read.delim("~/Desktop/MetaAnalysis_cc1.tbl", stringsAsFactors = FALSE)
eQTLs_all <- read.delim("~/Desktop/eQTLs_all.txt")
View(MetaAnalysis_cc1)
View(eQTLs_all)
gmirror(top=MetaAnalysis_cc1, bottom=eQTLs_all, tline=0.05/nrow(MetaAnalysis_cc1), bline=0.05/nrow(eQTLs_all),
    toptitle="GWAS Comparison Example: Data 1", bottomtitle = "GWAS Comparison Example: Data 2", 
    highlight_p = c(0.05/nrow(MetaAnalysis_cc1),0.05/nrow(eQTLs_all)), highlighter="green")
```

After running this code it stated 

Error in gmirror(top = MetaAnalysis_cc1, bottom = eQTLs_all, tline = 0.05/nrow(MetaAnalysis_cc1),  : 
  Please ensure both inputs have the same metadata columns.

**Comment by gaow** [comment]
@mgrasso24 have you been able to figure it out yet? It seems the error message is somewhat self-explanatory -- you need to make sure that the format for `top` and `bottom` are exactly the same , including column names.

**Comment by mgrasso24** [comment]
@gaow yep working on it right now! I was out sick for a couple of days but should finish this up soon!

**Comment by mgrasso24** [comment]
After removing the unnecessary columns and renaming them to match, I get this error. When I search how to figure out how to solve this error, I don't get any helpful solutions. Do you have any advice?

`install.packages("devtools")
devtools::install_github("hadley/devtools")
devtools::install_github('anastasia-lucas/hudson')
MetaAnalysis_cc1 <- read.delim("~/Downloads/MetaAnalysis_cc1.tbl", stringsAsFactors = FALSE)
eQTLs_all <- read.delim("~/Downloads/eQTLs_all.txt")
drop <- c("HetPVal","HetChiSq","HetISq","Allele1","Allele2","Weight","Zscore","Direction","HetDf")
mdf = MetaAnalysis_cc1[!(names(MetaAnalysis_cc1)%in% drop)]
drop <- c("SNPchromosome","SNPpos","featureName","featureChromosome","featurePositionStart","SpearmanRho")
edf = eQTLs_all[!(names(eQTLs_all)%in% drop)]
install.packages(c('dplyr', 'readxl'))
edfr = dplyr::rename(edf, "P.value" = "pValue", "MarkerName" = "SNPid")
library(hudson)
gmirror(top=edfr, bottom=mdf, tline=0.05/nrow(mdf), bline=0.05/nrow(edfr), 
toptitle="GWAS Comparison Example: Data 1", bottomtitle = "GWAS Comparison Example: Data 2", 
highlight_p = c(0.05/nrow(mdf),0.05/nrow(edfr)), highlighter="green")


` 
#Error in `$<-.data.frame`(`*tmp*`, "POS", value = numeric(0)) : 
  replacement has 0 rows, data has 67374347

**Comment by gaow** [comment]
@mgrasso24 in general there are two ways to try tackle this: check your input, and check the source code of `gmirror`.

Check your input: you've got two data frames `edfr` and `mdf`. You should compare it with the input from the example data in the gmirror package (let me know if they dont have any!), to make sure the number of columns are exactly the same and the headers as well (case sensitive!). You also check to make sure your two data frames have matching SNP IDs because otherwise there is no way to connect one data-set to another. 

Check the source code of gmirror: you can run code `gmirror` in R directly without parameters. IT's going to print all the source code of this function. You can then save this function into a file, but rename it to, eg `gmirror_mg` (mg is your initial; or you name it whatever). then you can modify the gmirror_mg to print more information for you before the error occurs. For example you can try to add lines like `print("here I am")` in between lines of the codes, then run the function as `gmirror_mg(top=...)` so you can pinpoint to exactly which line in the code that gives you an issue. Then you can see what data flows into that line in question, and try to fix it from there.

**Comment by mgrasso24** [comment]
> Check your input: you've got two data frames edfr and mdf. You should compare it with the input from the example data in the gmirror package (let me know if they dont have any!), to make sure the number of columns are exactly the same and the headers as well (case sensitive!). You also check to make sure your two data frames have matching SNP IDs because otherwise there is no way to connect one data-set to another.

@gaow I think I have an idea what the issue is. I looked at how many columns there were on the sample data used in the hudson plot. The columns used were SNP, CHR, POS, pvalue therefore, I changed the code name of datset to exactly the spelling of SNP and pvalue used yet I still get the error. Therefore, I feel as if the issue is that the dataset I have do not both have the Chromosome and Position each SNP lies on. Do you agree that is the possible issue for the error? 

 I will work on the checking the source of code as well but I suspect this is the issue because how would the code able to know which chromosome the SNP is located on without the information given?

```
install.packages("devtools")
devtools::install_github("hadley/devtools")
devtools::install_github('anastasia-lucas/hudson')
MetaAnalysis_cc1 <- read.delim("~/Downloads/MetaAnalysis_cc1.tbl", stringsAsFactors = FALSE)
eQTLs_all <- read.delim("~/Downloads/eQTLs_all.txt")
drop <- c("HetPVal","HetChiSq","HetISq","Allele1","Allele2","Weight","Zscore","Direction","HetDf")
mdf = MetaAnalysis_cc1[!(names(MetaAnalysis_cc1)%in% drop)]
drop <- c("SNPchromosome","SNPpos","featureName","featureChromosome","featurePositionStart","SpearmanRho")
edf = eQTLs_all[!(names(eQTLs_all)%in% drop)]
install.packages(c('dplyr', 'readxl'))
edfr = dplyr::rename(edf, "pvalue" = "pValue", "SNP" = "SNPid")
mdfr = dplyr::rename(mdf, "pvalue" = "P.value", "SNP" = "MarkerName")
library(hudson)
gmirror(top=edfr, bottom=mdfr, tline=0.05/nrow(mdfr), bline=0.05/nrow(edfr), 
toptitle="GWAS Comparison Example: Data 1", bottomtitle = "GWAS Comparison Example: Data 2", 
highlight_p = c(0.05/nrow(mdfr),0.05/nrow(edfr)), highlighter="green")

```

**Comment by gaow** [comment]
>  You also check to make sure your two data frames have matching SNP IDs because otherwise there is no way to connect one data-set to another.

See my comments above from my previous post. It sounds like a matching issue. There are two ways SNPs match each other: 1. by SNP ID, which in your case is `SNPid` in one data-set and `MarkerName` in the other data-set; and 2. by chromoosome and position. You may need to check the source code to verify which way it uses to match, then double check and figure out why they don't match with each other. For example simple things such as in one data-set chromosomes are given by eg `chr1` with the `chr` prefix and the other `1` without prefix. If they use SNP ID you need to make sure the SNP ID themselves have the same format -- not just that column names agree.

> how would the code able to know which chromosome the SNP is located on without the information given?

I dont get this questoin. The chromosome and position information are already provided in the dataset for each SNP.

**Comment by mgrasso24** [comment]
@gaow

Ok, I am running this now. I will let you know what happens. Thank you so much for taking the time to help me problem solve this!

**Comment by mgrasso24** [comment]
> I dont get this questoin. The chromosome and position information are already provided in the dataset for each SNP.

So after running everything the code used in the example data needs the POS and CHR which would be fine but only the eQTL data contains those. The GWAS study did not give the POS and CHR. 

Does that make sense? Sorry I did not explain it well originally.

**Comment by gaow** [comment]
I see. What does the data look like for GWAS? you can use `head` in `R` to display a few rows of sample data in [this notebook](https://github.com/mgrasso24/dyslexia-omics-integration/blob/main/analysis/20220825_hudson_plot_Gialluisi_Ng.ipynb) to show what it looks like. That will make communications clearer.

GWAS data should have chr and pos information, particularly if they are downloaded from GWAS Catalog. ... What's the status on the 23andme paper and data?

**Comment by mgrasso24** [comment]
Ok, I am updating the notebook now. However, it is taking a while to upload so I included a sc of what it shows below. When running head in displays: 

<img width="826" alt="Screen Shot 2022-09-10 at 16 53 05" src="https://user-images.githubusercontent.com/105136648/189501415-92bdb34f-ab52-4c04-a2b9-fac519e85569.png">

I ran the code with the eQTL and one of the sample datsets from the example and the plot works and no errors are given therefore the issue must be because of the lack of information in the GWAS study. I even added columns CHR/ POS to the eQTL givening the value "NA" to see if that would allow it to run but that was not the case.

**Comment by gaow** [comment]
we then basically have to provide the program a way to match SNPs. You stil lhave to verify which way it is used to match SNPs in the program (via ID or via chrom+position). If it is through the rsID you can make sure the eQTL IDs are also in terms of rsID (starting with `rs` followed by a number). You can also show the first few lines of the eQTL data to verify it. If you realize the code needs chrom and position instead of ID, what you can do is 1. to change the code to use IDs instead, or 2. to add to the GWAS data the chrom and position columns based on rsIDs -- you need to search online and figure out how to annotate SNP ID with chrom and position informatin. solution 1 sounds easier to me

**Comment by mgrasso24** [comment]
That makes a ton of sense thank you! I spent the day trying to solve this, and I did. I just uploaded the jupyter notebook to github!

I appreciate all your help!
