### ISSUE TITLE
Example analysis using coloc package

### ISSUE THREAD

**Issue by gaow** [mgrasso24/dyslexia-omics-integration#6]
Please take a look at the coloc package https://github.com/chr1swallace/coloc -- install it and make a notebook to perform an analysis using the sample data coloc package provides. In particular, please study the output of the coloc analysis try to understand at the high level what those results mean. You can try to dig it up from the reference papers coloc cites. It would be a substantial achievement if you can more or less understand what these results mean (I dont think all of my grad students understand them!). But don't push too hard if you cannot understand it on your own. We can talk at some point. 

For your information: when you study a statistical / computational model you want to understand what it does and how it does it. The "how" part is hard without the technical details you may learn in the future. But you should try to get the "what" part. There is a high level "what" part that you undersatnd already -- coloc is designed to detect and distinguish SNPs from its LD friends for its possible direct contributions to two complex traits at the same time, which in this case is gene expression and dyslexia. What i'm asking you to do now is to undersatnd the low level "what" by studying the output of the software to see exactly what it reports to answer the question. We will move on to real data analysis once you master these basics.

**Comment by gaow** [comment]
@mgrasso24 great -- can i suggest you make a table in the notebook above, using markdown syntax (google how to make a markdown table) and explain to the best of ur knowledge what each column means? Regarding your question: suppose you have this linear regression model y = xb + e where y is the phenotype, x is the genotype, b is the effect size of the geneotype and e is the non-genetic variations. Then you can estimate b as eg in your notation beta. VarBeta is the variance of beta of that estimate. sdY is the standard deviation of y, which, if y follows a standard normal distribution N(0,1), sdY will always be 1 -- somtimes people force y to follow N(0,1) by apply some transformations. This is known as "Normalization" in the context of GWAS. 

To understand roughly how to estimate beta, you can google search "least square estimate in linear regression". This is what you'll learn maybe the first day of your linear reggression analysis class.

**Comment by mgrasso24** [comment]
@gaow 

> can i suggest you make a table in the notebook above, using markdown syntax (google how to make a markdown table) and explain to the best of ur knowledge what each column means?

yes, I will get started on this! Thanks for your explanation, this makes so much more sense now!

**Comment by mgrasso24** [comment]
@gaow 

I was unable to do this earlier due to the holiday.  However, I added the table in my notebook! I want to go over what I know and still have questions. Therefore, I booked a meeting with you on Friday at 5 so we can go over what we have so far. I will send you a meeting agenda as soon as possible!
