### ISSUE TITLE
Meeting Action Items 20221009

### ISSUE THREAD

**Issue by mgrasso24** [mgrasso24/dyslexia-omics-integration#9]
@gaow 

I went through the columns of each dataset we have and the sample dataset and I have concluded:

Beta + LD
  Need for all datasets

Position + Chromosome
    Have for ⅔ not Gialluisi et al., (2021) GWAS study

Varbeta + sdY + Type
  Don't think need

Snp
  Have 

https://github.com/mgrasso24/dyslexia-omics-integration/blob/main/analysis/20220919_Testdata.R_for_coloc_analysis.ipynb

Let me know if this is right or if I am missing anything!

I am currently working on reading those articles and running the colco.

**Comment by gaow** [comment]
Very  good @mgrasso24 I think the immediate improvement you should make to your notebook is to add results: including showing the outputs, make some tables, and plots and most importantly comments of what you learn. The analysis should never end at the point that you get everything to run and complete. That's only the beginning. The science part only starts when you interpret the results. Even for simulated data, I would like you to try to interpret it and document.

**Comment by mgrasso24** [comment]
@gaow 

I am currently still running the colco and seeing what the results have shown, but I will definitely include all of what you noted above.

I just want to confirm that you agree we only need the Beta + LD for all datasets.

**Comment by gaow** [comment]
We need beta, sebeta and LD for all data-sets for the actual comoputation in coloc but we should always get the complete coordinates such as chr pos ref and alt, for whatever summary data we get. That four columns are "must-have".

**Comment by mgrasso24** [comment]
Got it! Sorry for the delay I was out sick for 4 days so I am swamped with catching up with schoolwork.

**Comment by gaow** [comment]
The 23andme paper says " validation in three independent cohorts (GenLang Consortium, CRS and NeuroDys)" -- the NeuroDys paper is the Gialluisi et al., (2021) GWAS. I wonder also if you could track data from GenLang Consortium, CRS and NeuroDys. If we can get these data, we can perform meta-analysis to combine with 23andme to get a even better set of summary stats, then to integrate with eQTLs ...

**Comment by mgrasso24** [comment]
Great idea! I will check on that right away.

**Comment by mgrasso24** [comment]
I uploaded the data that I was sent so far with the readme.txt
